#!/usr/bin/python

import cgi ,cgitb, os
from socket import *

buffersize = 125000

cgitb.enable()
form = cgi.FieldStorage()

id = str(form.getvalue('id'))
user = str(form.getvalue('user'))
stage = str(form.getvalue('stage'))


print "Content-type: text/html\n\n"


try:
	HOST = 'localhost'
	PORT = 50000

	ADDR = (HOST,PORT)

	cli = socket( AF_INET,SOCK_STREAM)

	# cli.setsockopt(SOL_SOCKET,SO_REUSEADDR, 1)

	# cli.settimeout(0.2)

	cli.connect((ADDR))

	data = cli.recv(buffersize)

	if data.lower().strip('\n').strip('\r') == 'ok':
		cli.send('agenda')
		data = cli.recv(buffersize)
		if data.lower().strip('\n').strip('\r') == 'ok':
			cli.send(id + '\n' + user + '\n' + stage)
			data = '1'
			while data:
				data = cli.recv(buffersize)
				print data
				if '</html>' in data:
					break

except:
	print "Location:../html/down.html\n\n"
