#!/usr/bin/python

import cgi ,cgitb, os
import json
from socket import *


cgitb.enable()
form = cgi.FieldStorage()

token = str(form.getvalue('token'))

# print "Content-type: text/html\n\n"

try:
	HOST = 'localhost'
	PORT = 50000

	ADDR = (HOST,PORT)

	cli = socket( AF_INET,SOCK_STREAM)
	cli.connect((ADDR))

	data = cli.recv(1024)

	if data.lower().strip('\n').strip('\r') == 'ok':
		cli.send('login')
		data = cli.recv(1024)
		if data.lower().strip('\n').strip('\r') == 'ok':


			cli.send(token)
			

			data = cli.recv(1024)

	print "Location:"+ data +"\n\n";

except:
	print "Location:../html/down.html\n\n"

