#!/usr/bin/python

import cgi ,cgitb, os
from socket import *


cgitb.enable()
form = cgi.FieldStorage()

country = str(form.getvalue('country')) 
id = str(form.getvalue('id')) 

buffersize = 400000

try:
	HOST = 'localhost'
	PORT = 50000

	ADDR = (HOST,PORT)

	cli = socket( AF_INET,SOCK_STREAM)
	cli.connect((ADDR))

	data = cli.recv(buffersize)

	if data.lower().strip('\n').strip('\r') == 'ok':
		cli.send('team')
		data = cli.recv(buffersize)
		if data.lower().strip('\n').strip('\r') == 'ok':
			cli.send(id + '\n' + country)
			data = cli.recv(buffersize)

	print "Content-type: text/html\n\n"
	print data

except:
	print "Location:../html/down.html\n\n"
